# Postgres deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-postgres
  template:
    metadata:
      labels:
        app: devops-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1
          env:
          - name: POSTGRES_PASSWORD
            value: Passw0rd2024!
          - name: POSTGRES_USER
            value: moviesReviews
          - name: POSTGRES_DB
            value: moviesReviews
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: devops-postgres
  ports:
    - port: 5432
---
# Web App deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-reviews-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-reviews-app
  template:
    metadata:
      labels:
        app: movies-reviews-app
    spec:
      containers:
        - name: movies-reviews-app
          image: pjruas/movies-review:v1
          env:
          - name: ASPNETCORE_HTTP_PORTS
            value: "8080"
          - name: ConnectionStrings__DefaultConnection
            value: "Host=postgres;Database=moviesReviews;Username=moviesReviews;Password=Passw0rd2024!"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: movies-reviews-app
spec:
  selector:
    app: movies-reviews-app
  ports:
    - port: 80
      targetPort: 8080
      # nodePort: 30000
  type: LoadBalancer