name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Main code Ceckout
        uses: actions/checkout@v4.1.7
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Image Build and Push to DockerHub
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            pjruas/movies-review:v4{{ github.run_number }}
            pjruas/movies-review:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: deploy
        run: echo "Application deploy"
