name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Main code Ceckout
        uses: actions/checkout@v4.1.7
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Container image building
        run: echo "Build app image"
      - name: image-publishing
        run: echo "Publish image to Docker Hub"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: deploy
        run: echo "Application deploy"
